#ifndef __CategoryFilters_H__
#define __CategoryFilters_H__

enum FilterCategory
{
	CATEGORY_DEFAULT = 0x0001,
	CATEGORY_PLAYER	 = 0x0002,
	CATEGORY_ENEMY   = 0x0004,
	CATEGORY_PBULLET = 0x0008,
	CATEGORY_EBULLET = 0x0010,
	CATEGORY_GROUND  = 0x0011,
	CATEGORY_NOCLIP  = 0X0012,
	CATEGORY_DEAD	 = 0x0014,
	CATEGORY_PICKUP  = 0x0018,

};

enum FilterMasks
{
	MASK_ALLCLIP		   = CATEGORY_DEFAULT | CATEGORY_PLAYER | CATEGORY_ENEMY | CATEGORY_PBULLET | CATEGORY_EBULLET | CATEGORY_GROUND,
	MASK_GROUND_NO_BULLETS = CATEGORY_DEFAULT | CATEGORY_PLAYER | CATEGORY_ENEMY | CATEGORY_GROUND | CATEGORY_DEAD,
	MASK_PLAYER            = CATEGORY_DEFAULT | CATEGORY_ENEMY | CATEGORY_EBULLET | CATEGORY_GROUND,
	MASK_ENEMY			   = CATEGORY_DEFAULT | CATEGORY_PLAYER | CATEGORY_PBULLET | CATEGORY_GROUND,
	MASK_DEAD			   = CATEGORY_GROUND,
	MASK_PBULLET           = CATEGORY_ENEMY,
	MASK_EBULLET		   = CATEGORY_PLAYER,
	MASK_PICKUP			   = CATEGORY_PLAYER,

};

#endif //__CategoryFilters_H__
